import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/components/Header";
import * as React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hi',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
