import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/components/Header";
import * as React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hi',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <main className="flex min-h-screen flex-col items-center justify-between p-10">
            <Header/>
            {children}
          </main>
      </body>
    </html>
  )
}
